### ISSUE TITLE
How to recompile the firmware

### ISSUE THREAD

**Issue by 4dvn** [DerFetzer/open-smartpad#2]
Is this source code support for stm32f103c8t6? Can you give more detail of compile the source code after upload bootloader?

**Comment by DerFetzer** [comment]
Hi @4dvn,

sorry for my late reply. I by mistake did not activate watching this repository so I got no notification for your issue.

The only difference is that your controller has half the flash if I remember correctly. Since the firmware is only about 20KB in size in release mode it should fit your processor as is. You should edit memory size in `memory.x` accordingly so that you get a linker error when the firmware exceeds flash size.
When compiled in debug mode the firmware does not even fit inside 128KB of flash.

Compilation should be done with a simple `cargo build --release`.
With the board connected over USB in bootloader mode (no actual program in flash or press and hold first pad in third row during power-up) it should be recognized as a HID device. Then you can use `hid-flash` from the bootloader repository. Use any COM port as it is not used but `hid-flash` checks if it is there.

Feel free to ask if further questions come up.

**Comment by 4dvn** [comment]
Hello, i'm building a diy custom board with 8x8 matrix buttons with leds but i have trouble with rgb, can you tell more about the rgb ic chip and type of rgb on this midi also the pinout of rgb?

**Comment by DerFetzer** [comment]
Hi,
please have a look at the schematic and pictures in the `hardware` folder. The ICs are simple shift registers with constant current sink (https://trgcomponents.com/products/products-detail/article/dm13c-led-display-2.html).
